scoop install googlechrome
scoop install slack
scoop install discord
scoop install vlc
scoop install jq
scoop install latex
scoop install sumatrapdf
scoop install gcloud
scoop install elixir
scoop install extras/vcredist2013
scoop install calibre
scoop install windows-terminal
scoop install obsidian